#!/bin/sh
umount /media/flash
scp build3:/home/zuav/src/apkr10/tmp/deploy/images/apkr10-installer-x86_64-generic.img /tmp/
dd if=/tmp/apkr10-installer-x86_64-generic.img of=/dev/sdb bs=1M oflag=direct
sync
sync
sync
