#!/bin/sh
#
# $1 -- path to the directory with data to put into iso image
# $2 -- full filename of the iso image
#
cd $1
/usr/bin/mkisofs -J -R -allow-lowercase -allow-multidot -iso-level 3 . > $2
cd -
